-- DROP USER APOLLOCONFIGDB;

CREATE USER APOLLOCONFIGDB
-- IDENTIFIED BY <password>
;

CREATE TABLE "ACCESSKEY" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"SECRET" NVARCHAR2(128) DEFAULT '' NOT NULL ENABLE, 
	"ISENABLED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT 'default', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C00128399" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128283" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128286" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128289" CHECK ("SECRET" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128292" CHECK ("ISENABLED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128295" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128298" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128301" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128304" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128306" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128414" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128415" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128416" CHECK ("SECRET" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128417" CHECK ("ISENABLED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128418" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128419" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128420" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128421" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128422" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129323" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129324" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129325" CHECK ("SECRET" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129326" CHECK ("ISENABLED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129327" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129328" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129329" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129330" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129331" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128399" ON "ACCESSKEY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "ACCESSKEY_DATACHANGE_LASTTIME" ON "ACCESSKEY" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "ACCESSKEY_UK_APPID_SECRET_DELETEDAT" ON "ACCESSKEY" ("APPID", "SECRET", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.ACCESSKEY IS '访问密钥';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.ID IS '自增主键';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.SECRET IS 'SECRET';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.ISENABLED IS '1: ENABLED, 0: DISABLED';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.ACCESSKEY.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "APP" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"NAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ORGID" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"ORGNAME" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"OWNERNAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"OWNEREMAIL" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128401" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128278" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128280" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128282" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128285" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128288" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128291" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128294" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128297" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128300" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128303" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128305" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128423" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128424" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128425" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128426" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128427" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128428" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128429" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128430" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128431" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128432" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128433" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129332" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129333" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129334" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129335" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129336" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129337" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129338" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129339" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129340" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129341" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129342" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128401" ON "APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "APP_DATACHANGE_LASTTIME" ON "APP" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "APP_IX_NAME" ON "APP" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "APP_UK_APPID_DELETEDAT" ON "APP" ("APPID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.APP IS '应用表';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.ID IS '主键';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.NAME IS '应用名';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.ORGID IS '部门ID';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.ORGNAME IS '部门名字';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.OWNERNAME IS 'OWNERNAME';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.OWNEREMAIL IS 'OWNEREMAIL';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.APP.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "APPNAMESPACE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(32) DEFAULT '' NOT NULL ENABLE, 
	"APPID" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"FORMAT" NVARCHAR2(32) DEFAULT 'properties' NOT NULL ENABLE, 
	"ISPUBLIC" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"COMMENT" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128400" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128277" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128279" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128281" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128284" CHECK ("FORMAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128287" CHECK ("ISPUBLIC" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128290" CHECK ("COMMENT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128293" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128296" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128299" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128302" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128434" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128435" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128436" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128437" CHECK ("FORMAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128438" CHECK ("ISPUBLIC" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128439" CHECK ("COMMENT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128440" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128441" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128442" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128443" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129343" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129344" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129345" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129346" CHECK ("FORMAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129347" CHECK ("ISPUBLIC" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129348" CHECK ("COMMENT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129349" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129350" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129351" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129352" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128400" ON "APPNAMESPACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "APPNAMESPACE_DATACHANGE_LASTTIME" ON "APPNAMESPACE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "APPNAMESPACE_NAME_APPID" ON "APPNAMESPACE" ("NAME", "APPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "APPNAMESPACE_UK_APPID_NAME_DELETEDAT" ON "APPNAMESPACE" ("APPID", "NAME", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.APPNAMESPACE IS '应用NAMESPACE定义';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.ID IS '自增主键';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.NAME IS 'NAMESPACE名字，注意，需要全局唯一';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.APPID IS 'APP ID';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.FORMAT IS 'NAMESPACE的FORMAT类型';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.ISPUBLIC IS 'NAMESPACE是否为公共';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.APPNAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "AUDIT" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"ENTITYNAME" NVARCHAR2(50) DEFAULT 'default' NOT NULL ENABLE, 
	"ENTITYID" NUMBER(11,0), 
	"OPNAME" NVARCHAR2(50) DEFAULT 'default' NOT NULL ENABLE, 
	"COMMENT" NVARCHAR2(500), 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128398" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128270" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128271" CHECK ("ENTITYNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128272" CHECK ("OPNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128273" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128274" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128275" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128276" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128444" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128445" CHECK ("ENTITYNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128446" CHECK ("OPNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128447" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128448" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128449" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128450" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129353" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129354" CHECK ("ENTITYNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129355" CHECK ("OPNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129356" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129357" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129358" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129359" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128398" ON "AUDIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "AUDIT_DATACHANGE_LASTTIME" ON "AUDIT" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB."AUDIT" IS '日志审计表';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".ID IS '主键';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".ENTITYNAME IS '表名';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".ENTITYID IS '记录ID';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".OPNAME IS '操作类型';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT"."COMMENT" IS '备注';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."AUDIT".DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "CLUSTER" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(32) DEFAULT '' NOT NULL ENABLE, 
	"APPID" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"PARENTCLUSTERID" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128402" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128307" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128308" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128309" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128310" CHECK ("PARENTCLUSTERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128311" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128312" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128313" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128314" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128451" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128452" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128453" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128454" CHECK ("PARENTCLUSTERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128455" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128456" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128457" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128458" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129360" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129361" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129362" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129363" CHECK ("PARENTCLUSTERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129364" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129365" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129366" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129367" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128402" ON "CLUSTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "CLUSTER_DATACHANGE_LASTTIME" ON "CLUSTER" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "CLUSTER_IX_PARENTCLUSTERID" ON "CLUSTER" ("PARENTCLUSTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "CLUSTER_UK_APPID_NAME_DELETEDAT" ON "CLUSTER" ("APPID", "NAME", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB."CLUSTER" IS '集群';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".ID IS '自增主键';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".NAME IS '集群名字';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".APPID IS 'APP ID';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".PARENTCLUSTERID IS '父CLUSTER';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."CLUSTER".DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "COMMIT" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"CHANGESETS" NCLOB NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"CLUSTERNAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"NAMESPACENAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"COMMENT" NVARCHAR2(500), 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT '' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT ' DEFAULT ' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128404" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128322" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128323" CHECK ("CHANGESETS" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128324" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128325" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128326" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128327" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128328" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128329" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128330" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128459" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128460" CHECK ("CHANGESETS" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128461" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128462" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128463" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128464" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128465" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128466" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128467" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129368" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129369" CHECK ("CHANGESETS" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129370" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129371" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129372" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129373" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129374" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129375" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129376" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("CHANGESETS") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_IL0000186849C00002$$" ON "COMMIT" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_C00128404" ON "COMMIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "COMMIT_APPID" ON "COMMIT" ("APPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "COMMIT_CLUSTERNAME" ON "COMMIT" ("CLUSTERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "COMMIT_DATACHANGE_LASTTIME" ON "COMMIT" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "COMMIT_NAMESPACENAME" ON "COMMIT" ("NAMESPACENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB."COMMIT" IS 'COMMIT 历史表';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".ID IS '主键';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".CHANGESETS IS '修改变更集';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".CLUSTERNAME IS 'CLUSTERNAME';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".NAMESPACENAME IS 'NAMESPACENAME';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT"."COMMENT" IS '备注';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."COMMIT".DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "GRAYRELEASERULE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"CLUSTERNAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"NAMESPACENAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"BRANCHNAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"RULES" NCLOB DEFAULT '[]', 
	"RELEASEID" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE, 
	"BRANCHSTATUS" NUMBER(4,0) DEFAULT 1, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128403" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128331" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128332" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128333" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128334" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128335" CHECK ("BRANCHNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128336" CHECK ("RELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128337" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128338" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128339" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128340" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128468" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128469" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128470" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128471" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128472" CHECK ("BRANCHNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128473" CHECK ("RELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128474" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128475" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128476" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128477" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129377" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129378" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129379" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129380" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129381" CHECK ("BRANCHNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129382" CHECK ("RELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129383" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129384" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129385" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129386" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("RULES") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_IL0000186852C00006$$" ON "GRAYRELEASERULE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_C00128403" ON "GRAYRELEASERULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "GRAYRELEASERULE_DATACHANGE_LASTTIME" ON "GRAYRELEASERULE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "GRAYRELEASERULE_IX_NAMESPACE" ON "GRAYRELEASERULE" ("APPID", "CLUSTERNAME", "NAMESPACENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.GRAYRELEASERULE IS '灰度规则表';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.ID IS '主键';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.CLUSTERNAME IS 'CLUSTER NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.NAMESPACENAME IS 'NAMESPACE NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.BRANCHNAME IS 'BRANCH NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.RULES IS '灰度规则';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.RELEASEID IS '灰度对应的RELEASE';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.BRANCHSTATUS IS '灰度分支状态: 0:删除分支,1:正在使用的规则 2：全量发布';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.GRAYRELEASERULE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "INSTANCE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"CLUSTERNAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACENTER" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"IP" NVARCHAR2(32) DEFAULT '' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C00128405" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128315" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128316" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128317" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128318" CHECK ("DATACENTER" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128319" CHECK ("IP" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128320" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128321" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128478" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128479" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128480" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128481" CHECK ("DATACENTER" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128482" CHECK ("IP" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128483" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128484" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129387" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129388" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129389" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129390" CHECK ("DATACENTER" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129391" CHECK ("IP" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129392" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129393" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128405" ON "INSTANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "INSTANCE_IX_DATACHANGE_LASTTIME" ON "INSTANCE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "INSTANCE_IX_IP" ON "INSTANCE" ("IP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "INSTANCE_IX_UNIQUE_KEY" ON "INSTANCE" ("APPID", "CLUSTERNAME", "IP", "DATACENTER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB."INSTANCE" IS '使用配置的应用实例';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".ID IS '自增ID';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".CLUSTERNAME IS 'CLUSTERNAME';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".DATACENTER IS 'DATA CENTER NAME';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".IP IS 'INSTANCE IP';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB."INSTANCE".DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "INSTANCECONFIG" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"INSTANCEID" NUMBER(11,0), 
	"CONFIGAPPID" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"CONFIGCLUSTERNAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"CONFIGNAMESPACENAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"RELEASEKEY" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"RELEASEDELIVERYTIME" DATE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C00128406" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128341" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128342" CHECK ("CONFIGAPPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128343" CHECK ("CONFIGCLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128344" CHECK ("CONFIGNAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128345" CHECK ("RELEASEKEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128346" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128347" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128485" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128486" CHECK ("CONFIGAPPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128487" CHECK ("CONFIGCLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128488" CHECK ("CONFIGNAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128489" CHECK ("RELEASEKEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128490" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128491" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129394" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129395" CHECK ("CONFIGAPPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129396" CHECK ("CONFIGCLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129397" CHECK ("CONFIGNAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129398" CHECK ("RELEASEKEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129399" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129400" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE INDEX "INSTANCECONFIG_IX_VALID_NAMESPACE" ON "INSTANCECONFIG" ("CONFIGAPPID", "CONFIGCLUSTERNAME", "CONFIGNAMESPACENAME", "DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SYS_C00128406" ON "INSTANCECONFIG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "INSTANCECONFIG_IX_DATACHANGE_LASTTIME" ON "INSTANCECONFIG" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "INSTANCECONFIG_IX_RELEASEKEY" ON "INSTANCECONFIG" ("RELEASEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "INSTANCECONFIG_IX_UNIQUE_KEY" ON "INSTANCECONFIG" ("INSTANCEID", "CONFIGAPPID", "CONFIGNAMESPACENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.INSTANCECONFIG IS '应用实例的配置信息';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.ID IS '自增ID';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.INSTANCEID IS 'INSTANCE ID';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.CONFIGAPPID IS 'CONFIG APP ID';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.CONFIGCLUSTERNAME IS 'CONFIG CLUSTER NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.CONFIGNAMESPACENAME IS 'CONFIG NAMESPACE NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.RELEASEKEY IS '发布的KEY';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.RELEASEDELIVERYTIME IS '配置获取时间';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.INSTANCECONFIG.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "ITEM" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"NAMESPACEID" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE, 
	"KEY" NVARCHAR2(128) DEFAULT 'default' NOT NULL ENABLE, 
	"VALUE" NCLOB NOT NULL ENABLE, 
	"COMMENT" NCLOB DEFAULT '', 
	"LINENUM" NUMBER(11,0) DEFAULT 0, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '0', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128407" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128348" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128349" CHECK ("NAMESPACEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128350" CHECK ("KEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128351" CHECK ("VALUE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128352" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128353" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128354" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128355" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128492" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128493" CHECK ("NAMESPACEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128494" CHECK ("KEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128495" CHECK ("VALUE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128496" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128497" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128498" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128499" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129401" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129402" CHECK ("NAMESPACEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129403" CHECK ("KEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129404" CHECK ("VALUE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129405" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129406" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129407" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129408" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("VALUE") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("COMMENT") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_C00128407" ON "ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "ITEM_DATACHANGE_LASTTIME" ON "ITEM" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "ITEM_IX_GROUPID" ON "ITEM" ("NAMESPACEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SYS_IL0000186857C00005$$" ON "ITEM" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_IL0000186857C00004$$" ON "ITEM" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE APOLLOCONFIGDB.ITEM IS '配置项目';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.ID IS '自增ID';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.NAMESPACEID IS '集群NAMESPACEID';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM."KEY" IS '配置项KEY';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.VALUE IS '配置项值';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.LINENUM IS '行号';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.ITEM.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "NAMESPACE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"CLUSTERNAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"NAMESPACENAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128408" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128356" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128357" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128358" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128359" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128360" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128361" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128362" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128363" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128500" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128501" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128502" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128503" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128504" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128505" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128506" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128507" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129409" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129410" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129411" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129412" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129413" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129414" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129415" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129416" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128408" ON "NAMESPACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "NAMESPACE_DATACHANGE_LASTTIME" ON "NAMESPACE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "NAMESPACE_IX_NAMESPACENAME" ON "NAMESPACE" ("NAMESPACENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "NAMESPACE_UK_APPID_CLUSTERNAME_NAMESPACENAME_DELETEDAT" ON "NAMESPACE" ("APPID", "CLUSTERNAME", "NAMESPACENAME", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.NAMESPACE IS '命名空间';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.ID IS '自增主键';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.CLUSTERNAME IS 'CLUSTER NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.NAMESPACENAME IS 'NAMESPACE NAME';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "NAMESPACELOCK" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"NAMESPACEID" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0', 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C00128409" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128364" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128365" CHECK ("NAMESPACEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128366" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128367" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128368" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128508" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128509" CHECK ("NAMESPACEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128510" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128511" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128512" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129417" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129418" CHECK ("NAMESPACEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129419" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129420" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129421" CHECK ("DELETEDAT" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

CREATE UNIQUE INDEX "SYS_C00128409" ON "NAMESPACELOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "NAMESPACELOCK_DATACHANGE_LASTTIME" ON "NAMESPACELOCK" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "NAMESPACELOCK_UK_NAMESPACEID_DELETEDAT" ON "NAMESPACELOCK" ("NAMESPACEID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;

COMMENT ON TABLE APOLLOCONFIGDB.NAMESPACELOCK IS 'NAMESPACE的编辑锁';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.ID IS '自增ID';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.NAMESPACEID IS '集群NAMESPACEID';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.ISDELETED IS '软删除';
COMMENT ON COLUMN APOLLOCONFIGDB.NAMESPACELOCK.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';

CREATE TABLE "RELEASE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"RELEASEKEY" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"NAME" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"COMMENT" NVARCHAR2(256), 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"CLUSTERNAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"NAMESPACENAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"CONFIGURATIONS" NCLOB NOT NULL ENABLE, 
	"ISABANDONED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128410" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128371" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128373" CHECK ("RELEASEKEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128375" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128377" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128379" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128381" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128382" CHECK ("CONFIGURATIONS" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128384" CHECK ("ISABANDONED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128386" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128388" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128390" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128392" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128513" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128514" CHECK ("RELEASEKEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128515" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128516" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128517" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128518" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128519" CHECK ("CONFIGURATIONS" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128520" CHECK ("ISABANDONED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128521" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128522" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128523" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128524" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129422" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129423" CHECK ("RELEASEKEY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129424" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129425" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129426" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129427" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129428" CHECK ("CONFIGURATIONS" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129429" CHECK ("ISABANDONED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129430" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129431" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129432" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129433" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("CONFIGURATIONS") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_C00128410" ON "RELEASE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "RELEASE_APPID_CLUSTERNAME_GROUPNAME" ON "RELEASE" ("APPID", "CLUSTERNAME", "NAMESPACENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "RELEASE_DATACHANGE_LASTTIME" ON "RELEASE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "RELEASE_UK_RELEASEKEY_DELETEDAT" ON "RELEASE" ("RELEASEKEY", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SYS_IL0000186864C00008$$" ON "RELEASE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE APOLLOCONFIGDB."RELEASE" IS '发布';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".ID IS '自增主键';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".RELEASEKEY IS '发布的KEY';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".NAME IS '发布名字';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE"."COMMENT" IS '发布说明';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".CLUSTERNAME IS 'CLUSTERNAME';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".NAMESPACENAME IS 'NAMESPACENAME';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".CONFIGURATIONS IS '发布配置';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".ISABANDONED IS '是否废弃';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB."RELEASE".DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "RELEASEHISTORY" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"CLUSTERNAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"NAMESPACENAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"BRANCHNAME" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"RELEASEID" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE, 
	"PREVIOUSRELEASEID" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE, 
	"OPERATION" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"OPERATIONCONTEXT" NCLOB NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128411" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128369" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128370" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128372" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128374" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128376" CHECK ("BRANCHNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128378" CHECK ("RELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128380" CHECK ("PREVIOUSRELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128383" CHECK ("OPERATION" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128385" CHECK ("OPERATIONCONTEXT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128387" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128389" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128391" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128393" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128525" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128526" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128527" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128528" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128529" CHECK ("BRANCHNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128530" CHECK ("RELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128531" CHECK ("PREVIOUSRELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128532" CHECK ("OPERATION" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128533" CHECK ("OPERATIONCONTEXT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128534" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128535" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128536" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128537" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129434" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129435" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129436" CHECK ("CLUSTERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129437" CHECK ("NAMESPACENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129438" CHECK ("BRANCHNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129439" CHECK ("RELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129440" CHECK ("PREVIOUSRELEASEID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129441" CHECK ("OPERATION" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129442" CHECK ("OPERATIONCONTEXT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129443" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129444" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129445" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129446" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("OPERATIONCONTEXT") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_C00128411" ON "RELEASEHISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "RELEASEHISTORY_IX_DATACHANGE_LASTTIME" ON "RELEASEHISTORY" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "RELEASEHISTORY_IX_NAMESPACE" ON "RELEASEHISTORY" ("APPID", "CLUSTERNAME", "NAMESPACENAME", "BRANCHNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "RELEASEHISTORY_IX_RELEASEID" ON "RELEASEHISTORY" ("RELEASEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SYS_IL0000186867C00009$$" ON "RELEASEHISTORY" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE APOLLOCONFIGDB.RELEASEHISTORY IS '发布历史';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.ID IS '自增ID';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.CLUSTERNAME IS 'CLUSTERNAME';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.NAMESPACENAME IS 'NAMESPACENAME';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.BRANCHNAME IS '发布分支名';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.RELEASEID IS '关联的RELEASE ID';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.PREVIOUSRELEASEID IS '前一次发布的RELEASEID';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.OPERATION IS '发布类型，0: 普通发布，1: 回滚，2: 灰度发布，3: 灰度规则更新，4: 灰度合并回主分支发布，5: 主分支发布灰度自动发布，6: 主分支回滚灰度自动发布，7: 放弃灰度';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.OPERATIONCONTEXT IS '发布上下文信息';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEHISTORY.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "RELEASEMESSAGE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"MESSAGE" NCLOB DEFAULT '' NOT NULL ENABLE, 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C00128412" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128394" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128395" CHECK ("MESSAGE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128396" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128538" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128539" CHECK ("MESSAGE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128540" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129447" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129448" CHECK ("MESSAGE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129449" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_C00128412" ON "RELEASEMESSAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "RELEASEMESSAGE_DATACHANGE_LASTTIME" ON "RELEASEMESSAGE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SYS_IL0000186870C00002$$" ON "RELEASEMESSAGE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE APOLLOCONFIGDB.RELEASEMESSAGE IS '发布消息';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEMESSAGE.ID IS '自增主键';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEMESSAGE.MESSAGE IS '发布的消息内容';
COMMENT ON COLUMN APOLLOCONFIGDB.RELEASEMESSAGE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "SERVERCONFIG" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"KEY" NVARCHAR2(64) DEFAULT 'default', 
	"CLUSTER" NVARCHAR2(32) DEFAULT 'default', 
	"VALUE" NCLOB DEFAULT 'default', 
	"COMMENT" NCLOB DEFAULT '', 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default', 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00128413" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB"  ENABLE, 
	 CONSTRAINT "SYS_C00128397" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128541" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128733" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129450" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129451" CHECK ("ISDELETED" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
 LOB ("VALUE") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("COMMENT") STORE AS SECUREFILE (
  TABLESPACE "APOLLOCONFIGDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "SYS_C00128413" ON "SERVERCONFIG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE INDEX "SERVERCONFIG_DATACHANGE_LASTTIME" ON "SERVERCONFIG" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SERVERCONFIG_UK_KEY_CLUSTER_DELETEDAT" ON "SERVERCONFIG" ("KEY", "CLUSTER", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" ;
  CREATE UNIQUE INDEX "SYS_IL0000186873C00005$$" ON "SERVERCONFIG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_IL0000186873C00004$$" ON "SERVERCONFIG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOCONFIGDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE APOLLOCONFIGDB.SERVERCONFIG IS '配置服务自身配置';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.ID IS '自增ID';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG."KEY" IS '配置项KEY';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG."CLUSTER" IS '配置对应的集群，DEFAULT为不针对特定的集群';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.VALUE IS '配置项值';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOCONFIGDB.SERVERCONFIG.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE SEQUENCE APOLLOCONFIGDB.ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
