/*
 Navicat Premium Data Transfer

 Source Server         : APOLLOCONFIGDB
 Source Server Type    : Oracle
 Source Server Version : 120200 (Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production)
 Source Host           : 192.168.80.73:1521
 Source Schema         : APOLLOPORTALDB

 Target Server Type    : Oracle
 Target Server Version : 120200 (Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production)
 File Encoding         : 65001

 Date: 18/05/2023 10:38:52
*/


-- ----------------------------
-- Table structure for APP
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."APP";
CREATE TABLE "APOLLOPORTALDB"."APP" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "ORGID" NVARCHAR2(32) VISIBLE NOT NULL,
  "ORGNAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "OWNERNAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "OWNEREMAIL" NVARCHAR2(500) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."NAME" IS '应用名';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."ORGID" IS '部门ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."ORGNAME" IS '部门名字';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."OWNERNAME" IS 'OWNERNAME';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."OWNEREMAIL" IS 'OWNEREMAIL';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."APP"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."APP" IS '应用表';

-- ----------------------------
-- Records of APP
-- ----------------------------

-- ----------------------------
-- Table structure for APPNAMESPACE
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."APPNAMESPACE";
CREATE TABLE "APOLLOPORTALDB"."APPNAMESPACE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "FORMAT" NVARCHAR2(32) VISIBLE NOT NULL,
  "ISPUBLIC" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "COMMENT" NVARCHAR2(64) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."NAME" IS 'NAMESPACE名字，注意，需要全局唯一';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."APPID" IS 'APP ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."FORMAT" IS 'NAMESPACE的FORMAT类型';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."ISPUBLIC" IS 'NAMESPACE是否为公共';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."COMMENT" IS '注释';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."APPNAMESPACE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."APPNAMESPACE" IS '应用NAMESPACE定义';

-- ----------------------------
-- Records of APPNAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for AUTHORITIES
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."AUTHORITIES";
CREATE TABLE "APOLLOPORTALDB"."AUTHORITIES" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "AUTHORITY" NVARCHAR2(50) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."AUTHORITIES"."ID" IS '自增ID';

-- ----------------------------
-- Records of AUTHORITIES
-- ----------------------------
INSERT INTO "APOLLOPORTALDB"."AUTHORITIES" VALUES ('1', 'apollo', 'ROLE_user');

-- ----------------------------
-- Table structure for CONSUMER
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."CONSUMER";
CREATE TABLE "APOLLOPORTALDB"."CONSUMER" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "ORGID" NVARCHAR2(32) VISIBLE NOT NULL,
  "ORGNAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "OWNERNAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "OWNEREMAIL" NVARCHAR2(500) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."NAME" IS '应用名';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."ORGID" IS '部门ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."ORGNAME" IS '部门名字';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."OWNERNAME" IS 'OWNERNAME';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."OWNEREMAIL" IS 'OWNEREMAIL';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMER"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."CONSUMER" IS '开放API消费者';

-- ----------------------------
-- Records of CONSUMER
-- ----------------------------

-- ----------------------------
-- Table structure for CONSUMERAUDIT
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."CONSUMERAUDIT";
CREATE TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CONSUMERID" NUMBER(11,0) VISIBLE,
  "URI" NCLOB VISIBLE NOT NULL,
  "METHOD" NVARCHAR2(16) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERAUDIT"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERAUDIT"."CONSUMERID" IS 'CONSUMER ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERAUDIT"."URI" IS '访问的URI';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERAUDIT"."METHOD" IS '访问的METHOD';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERAUDIT"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERAUDIT"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" IS 'CONSUMER审计表';

-- ----------------------------
-- Records of CONSUMERAUDIT
-- ----------------------------

-- ----------------------------
-- Table structure for CONSUMERROLE
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."CONSUMERROLE";
CREATE TABLE "APOLLOPORTALDB"."CONSUMERROLE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CONSUMERID" NUMBER(11,0) VISIBLE,
  "ROLEID" NUMBER(11,0) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."CONSUMERID" IS 'CONSUMER ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."ROLEID" IS 'ROLE ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERROLE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."CONSUMERROLE" IS 'CONSUMER和ROLE的绑定表';

-- ----------------------------
-- Records of CONSUMERROLE
-- ----------------------------

-- ----------------------------
-- Table structure for CONSUMERTOKEN
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."CONSUMERTOKEN";
CREATE TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CONSUMERID" NUMBER(11,0) VISIBLE,
  "TOKEN" NVARCHAR2(128) VISIBLE NOT NULL,
  "EXPIRES" DATE VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."CONSUMERID" IS 'CONSUMERID';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."TOKEN" IS 'TOKEN';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."EXPIRES" IS 'TOKEN失效时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."CONSUMERTOKEN"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" IS 'CONSUMER TOKEN表';

-- ----------------------------
-- Records of CONSUMERTOKEN
-- ----------------------------

-- ----------------------------
-- Table structure for FAVORITE
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."FAVORITE";
CREATE TABLE "APOLLOPORTALDB"."FAVORITE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "USERID" NVARCHAR2(32) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "POSITION" NUMBER(11,0) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."USERID" IS '收藏的用户';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."POSITION" IS '收藏顺序';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."FAVORITE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."FAVORITE" IS '应用收藏表';

-- ----------------------------
-- Records of FAVORITE
-- ----------------------------

-- ----------------------------
-- Table structure for PERMISSION
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."PERMISSION";
CREATE TABLE "APOLLOPORTALDB"."PERMISSION" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "PERMISSIONTYPE" NVARCHAR2(32) VISIBLE NOT NULL,
  "TARGETID" NVARCHAR2(256) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."PERMISSIONTYPE" IS '权限类型';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."TARGETID" IS '权限对象类型';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."PERMISSION"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."PERMISSION" IS 'PERMISSION表';

-- ----------------------------
-- Records of PERMISSION
-- ----------------------------

-- ----------------------------
-- Table structure for ROLE
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."ROLE";
CREATE TABLE "APOLLOPORTALDB"."ROLE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "ROLENAME" NVARCHAR2(256) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."ROLENAME" IS 'ROLE NAME';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."ROLE" IS '角色表';

-- ----------------------------
-- Records of ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for ROLEPERMISSION
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."ROLEPERMISSION";
CREATE TABLE "APOLLOPORTALDB"."ROLEPERMISSION" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "ROLEID" NUMBER(11,0) VISIBLE,
  "PERMISSIONID" NUMBER(11,0) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."ROLEID" IS 'ROLE ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."PERMISSIONID" IS 'PERMISSION ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."ROLEPERMISSION"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."ROLEPERMISSION" IS '角色和权限的绑定表';

-- ----------------------------
-- Records of ROLEPERMISSION
-- ----------------------------

-- ----------------------------
-- Table structure for SERVERCONFIG
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."SERVERCONFIG";
CREATE TABLE "APOLLOPORTALDB"."SERVERCONFIG" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "KEY" NVARCHAR2(64) VISIBLE,
  "VALUE" NCLOB VISIBLE,
  "COMMENT" NCLOB VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."KEY" IS '配置项KEY';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."VALUE" IS '配置项值';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."COMMENT" IS '注释';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."SERVERCONFIG"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."SERVERCONFIG" IS '配置服务自身配置';

-- ----------------------------
-- Records of SERVERCONFIG
-- ----------------------------
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('1', 'apollo.portal.envs', 'dev', '可支持的环境列表', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('2', 'organizations', '[{"orgId":"TEST1","orgName":"样例部门1"},{"orgId":"TEST2","orgName":"样例部门2"}]', '部门列表', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('3', 'superAdmin', 'apollo', 'Portal超级管理员', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('4', 'api.readTimeout', '10000', 'http接口read timeout', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('5', 'consumer.token.salt', 'someSalt', 'consumer token salt', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('6', 'admin.createPrivateNamespace.switch', 'true', '是否允许项目管理员创建私有namespace', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('7', 'configView.memberOnly.envs', 'pro', '只对项目成员显示配置信息的环境列表，多个env以英文逗号分隔', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOPORTALDB"."SERVERCONFIG" VALUES ('8', 'apollo.portal.meta.servers', '{}', '各环境Meta Service列表', '0', '0', 'default', TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:24', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for SPRING_SESSION
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."SPRING_SESSION";
CREATE TABLE "APOLLOPORTALDB"."SPRING_SESSION" (
  "PRIMARY_ID" CHAR(36 BYTE) VISIBLE NOT NULL,
  "SESSION_ID" CHAR(36 BYTE) VISIBLE NOT NULL,
  "CREATION_TIME" NUMBER(19,0) VISIBLE NOT NULL,
  "LAST_ACCESS_TIME" NUMBER(19,0) VISIBLE NOT NULL,
  "MAX_INACTIVE_INTERVAL" NUMBER(10,0) VISIBLE NOT NULL,
  "EXPIRY_TIME" NUMBER(19,0) VISIBLE NOT NULL,
  "PRINCIPAL_NAME" VARCHAR2(100 CHAR) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SPRING_SESSION
-- ----------------------------

-- ----------------------------
-- Table structure for SPRING_SESSION_ATTRIBUTES
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES";
CREATE TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" (
  "SESSION_PRIMARY_ID" CHAR(36 BYTE) VISIBLE NOT NULL,
  "ATTRIBUTE_NAME" VARCHAR2(200 CHAR) VISIBLE NOT NULL,
  "ATTRIBUTE_BYTES" BLOB VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SPRING_SESSION_ATTRIBUTES
-- ----------------------------

-- ----------------------------
-- Table structure for USERROLE
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."USERROLE";
CREATE TABLE "APOLLOPORTALDB"."USERROLE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "USERID" NVARCHAR2(128) VISIBLE,
  "ROLEID" NUMBER(11,0) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."USERID" IS '用户身份标识';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."ROLEID" IS 'ROLE ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERROLE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOPORTALDB"."USERROLE" IS '用户和ROLE的绑定表';

-- ----------------------------
-- Records of USERROLE
-- ----------------------------

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "APOLLOPORTALDB"."USERS";
CREATE TABLE "APOLLOPORTALDB"."USERS" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "PASSWORD" NVARCHAR2(512) VISIBLE NOT NULL,
  "USERDISPLAYNAME" NVARCHAR2(512) VISIBLE NOT NULL,
  "EMAIL" NVARCHAR2(64) VISIBLE NOT NULL,
  "ENABLED" NUMBER(4,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOPORTALDB"."USERS"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERS"."USERNAME" IS '用户登录账户';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERS"."PASSWORD" IS '密码';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERS"."USERDISPLAYNAME" IS '用户名称';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERS"."EMAIL" IS '邮箱地址';
COMMENT ON COLUMN "APOLLOPORTALDB"."USERS"."ENABLED" IS '是否有效';
COMMENT ON TABLE "APOLLOPORTALDB"."USERS" IS '用户表';

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "APOLLOPORTALDB"."USERS" VALUES ('1', 'apollo', '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS', 'apollo', 'apollo@acme.com', '1');

-- ----------------------------
-- Sequence structure for ID_SEQ
-- ----------------------------
DROP SEQUENCE "APOLLOPORTALDB"."ID_SEQ";
CREATE SEQUENCE "APOLLOPORTALDB"."ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table APP
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127575" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APP
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127480" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127481" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127482" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127483" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127484" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127485" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127486" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127487" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127488" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127489" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127491" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127790" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127791" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127792" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127793" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127794" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127795" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127796" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127797" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127798" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127799" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00127800" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129035" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129036" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129037" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129038" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129039" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129040" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129041" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129042" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129043" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129044" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APP" ADD CONSTRAINT "SYS_C00129045" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APP
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."APP_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."APP" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."APP_IX_NAME_INDEX"
  ON "APOLLOPORTALDB"."APP" ("NAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."APP_UK_APPID_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."APP" ("APPID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127576" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127490" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127493" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127495" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127497" CHECK ("FORMAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127499" CHECK ("ISPUBLIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127501" CHECK ("COMMENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127503" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127505" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127507" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127509" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127801" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127802" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127803" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127804" CHECK ("FORMAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127805" CHECK ("ISPUBLIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127806" CHECK ("COMMENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127807" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127808" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127809" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00127810" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129046" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129047" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129048" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129049" CHECK ("FORMAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129050" CHECK ("ISPUBLIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129051" CHECK ("COMMENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129052" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129053" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129054" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00129055" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APPNAMESPACE
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."DATAAPPNAMESPACE_CHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."APPNAMESPACE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."DATAAPPNAMESPACE_NAME_APPID_INDEX"
  ON "APOLLOPORTALDB"."APPNAMESPACE" ("NAME" ASC, "APPID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."DATAAPPNAMESPACE_UK_APPID_NAME_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."APPNAMESPACE" ("APPID" ASC, "NAME" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTHORITIES
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127574" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table AUTHORITIES
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127477" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127478" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127479" CHECK ("AUTHORITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127811" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127812" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00127813" CHECK ("AUTHORITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00129056" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00129057" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."AUTHORITIES" ADD CONSTRAINT "SYS_C00129058" CHECK ("AUTHORITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CONSUMER
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127577" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONSUMER
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127492" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127494" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127496" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127498" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127500" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127502" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127504" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127506" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127508" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127510" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127511" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127814" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127815" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127816" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127817" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127818" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127819" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127820" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127821" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127822" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127823" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00127824" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129059" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129060" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129061" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129062" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129063" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129064" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129065" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129066" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129067" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129068" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMER" ADD CONSTRAINT "SYS_C00129069" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONSUMER
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."AUTHORITIES_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."CONSUMER" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."AUTHORITIES_UK_APPID_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."CONSUMER" ("APPID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONSUMERAUDIT
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127578" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONSUMERAUDIT
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127512" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127513" CHECK ("URI" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127514" CHECK ("METHOD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127515" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127825" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127826" CHECK ("URI" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127827" CHECK ("METHOD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00127828" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00129070" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00129071" CHECK ("URI" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00129072" CHECK ("METHOD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERAUDIT" ADD CONSTRAINT "SYS_C00129073" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONSUMERAUDIT
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."CONSUMERAUDIT_IX_CONSUMERID_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERAUDIT" ("CONSUMERID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."CONSUMERAUDIT_IX_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERAUDIT" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONSUMERROLE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127581" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONSUMERROLE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127517" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127520" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127523" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127526" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127529" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127829" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127830" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127831" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127832" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00127833" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00129074" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00129075" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00129076" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00129077" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERROLE" ADD CONSTRAINT "SYS_C00129078" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONSUMERROLE
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."CONSUMERROLE_IX_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERROLE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."CONSUMERROLE_IX_ROLEID_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERROLE" ("ROLEID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."CONSUMERROLE_UK_CONSUMERID_ROLEID_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERROLE" ("CONSUMERID" ASC, "ROLEID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONSUMERTOKEN
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127579" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONSUMERTOKEN
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127518" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127521" CHECK ("TOKEN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127524" CHECK ("EXPIRES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127527" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127530" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127533" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127535" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127834" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127835" CHECK ("TOKEN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127836" CHECK ("EXPIRES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127837" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127838" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127839" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00127840" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129079" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129080" CHECK ("TOKEN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129081" CHECK ("EXPIRES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129082" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129083" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129084" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."CONSUMERTOKEN" ADD CONSTRAINT "SYS_C00129085" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONSUMERTOKEN
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."CONSUMERTOKEN_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERTOKEN" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."CONSUMERTOKEN_UK_TOKEN_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."CONSUMERTOKEN" ("TOKEN" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table FAVORITE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127580" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FAVORITE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127516" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127519" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127522" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127525" CHECK ("POSITION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127528" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127531" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127534" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127537" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127841" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127842" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127843" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127844" CHECK ("POSITION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127845" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127846" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127847" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00127848" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129086" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129087" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129088" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129089" CHECK ("POSITION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129090" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129091" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129092" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."FAVORITE" ADD CONSTRAINT "SYS_C00129093" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table FAVORITE
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."FAVORITE_APPID_INDEX"
  ON "APOLLOPORTALDB"."FAVORITE" ("APPID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."FAVORITE_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."FAVORITE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."FAVORITE_UK_USERID_APPID_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."FAVORITE" ("USERID" ASC, "APPID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table PERMISSION
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127582" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PERMISSION
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127532" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127536" CHECK ("PERMISSIONTYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127538" CHECK ("TARGETID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127539" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127540" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127541" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127542" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127849" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127850" CHECK ("PERMISSIONTYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127851" CHECK ("TARGETID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127852" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127853" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127854" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00127855" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129094" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129095" CHECK ("PERMISSIONTYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129096" CHECK ("TARGETID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129097" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129098" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129099" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."PERMISSION" ADD CONSTRAINT "SYS_C00129100" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table PERMISSION
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."PERMISSION_IX_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."PERMISSION" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."PERMISSION_UK_TARGETID_PERMISSIONTYPE_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."PERMISSION" ("TARGETID" ASC, "PERMISSIONTYPE" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table ROLE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127583" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ROLE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127543" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127544" CHECK ("ROLENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127545" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127546" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127547" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127548" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127856" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127857" CHECK ("ROLENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127858" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127859" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127860" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00127861" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00129101" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00129102" CHECK ("ROLENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00129103" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00129104" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00129105" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLE" ADD CONSTRAINT "SYS_C00129106" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ROLE
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."ROLE_IX_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."ROLE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."ROLE_UK_ROLENAME_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."ROLE" ("ROLENAME" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table ROLEPERMISSION
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127585" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ROLEPERMISSION
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127555" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127556" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127557" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127558" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127560" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127862" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127863" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127864" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127865" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00127866" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00129107" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00129108" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00129109" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00129110" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."ROLEPERMISSION" ADD CONSTRAINT "SYS_C00129111" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ROLEPERMISSION
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."ROLEPERMISSION_IX_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."ROLEPERMISSION" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."ROLEPERMISSION_IX_PERMISSIONID_INDEX"
  ON "APOLLOPORTALDB"."ROLEPERMISSION" ("PERMISSIONID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."ROLEPERMISSION_UK_ROLEID_PERMISSIONID_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."ROLEPERMISSION" ("ROLEID" ASC, "PERMISSIONID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00127586" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00127559" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00127867" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00128732" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00129112" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00129113" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SERVERCONFIG
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."SERVERCONFIG_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."SERVERCONFIG" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."SERVERCONFIG_UK_KEY_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."SERVERCONFIG" ("KEY" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table SPRING_SESSION
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SPRING_SESSION_PK" PRIMARY KEY ("PRIMARY_ID");

-- ----------------------------
-- Checks structure for table SPRING_SESSION
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00127980" CHECK ("PRIMARY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00127981" CHECK ("SESSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00127982" CHECK ("CREATION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00127983" CHECK ("LAST_ACCESS_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00127984" CHECK ("MAX_INACTIVE_INTERVAL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00127985" CHECK ("EXPIRY_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00128813" CHECK ("PRIMARY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00128814" CHECK ("SESSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00128815" CHECK ("CREATION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00128816" CHECK ("LAST_ACCESS_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00128817" CHECK ("MAX_INACTIVE_INTERVAL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION" ADD CONSTRAINT "SYS_C00128818" CHECK ("EXPIRY_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SPRING_SESSION
-- ----------------------------
CREATE UNIQUE INDEX "APOLLOPORTALDB"."SPRING_SESSION_IX1"
  ON "APOLLOPORTALDB"."SPRING_SESSION" ("SESSION_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."SPRING_SESSION_IX2"
  ON "APOLLOPORTALDB"."SPRING_SESSION" ("EXPIRY_TIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."SPRING_SESSION_IX3"
  ON "APOLLOPORTALDB"."SPRING_SESSION" ("PRINCIPAL_NAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table SPRING_SESSION_ATTRIBUTES
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SPRING_SESSION_ATTRIBUTES_PK" PRIMARY KEY ("SESSION_PRIMARY_ID", "ATTRIBUTE_NAME");

-- ----------------------------
-- Checks structure for table SPRING_SESSION_ATTRIBUTES
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SYS_C00127987" CHECK ("SESSION_PRIMARY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SYS_C00127988" CHECK ("ATTRIBUTE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SYS_C00127989" CHECK ("ATTRIBUTE_BYTES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SYS_C00129114" CHECK ("SESSION_PRIMARY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SYS_C00129115" CHECK ("ATTRIBUTE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SYS_C00129116" CHECK ("ATTRIBUTE_BYTES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERROLE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127588" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table USERROLE
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127564" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127565" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127566" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127567" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127568" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127868" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127869" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127870" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127871" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00127872" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00129117" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00129118" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00129119" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00129120" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERROLE" ADD CONSTRAINT "SYS_C00129121" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table USERROLE
-- ----------------------------
CREATE INDEX "APOLLOPORTALDB"."USERROLE_IX_DATACHANGE_LASTTIME_INDEX"
  ON "APOLLOPORTALDB"."USERROLE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOPORTALDB"."USERROLE_IX_ROLEID_INDEX"
  ON "APOLLOPORTALDB"."USERROLE" ("ROLEID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOPORTALDB"."USERROLE_UK_USERID_ROLEID_DELETEDAT_INDEX"
  ON "APOLLOPORTALDB"."USERROLE" ("USERID" ASC, "ROLEID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127589" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127569" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127570" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127571" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127572" CHECK ("USERDISPLAYNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127573" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127873" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127874" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127875" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127876" CHECK ("USERDISPLAYNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00127877" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00129122" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00129123" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00129124" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00129125" CHECK ("USERDISPLAYNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOPORTALDB"."USERS" ADD CONSTRAINT "SYS_C00129126" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table USERS
-- ----------------------------
CREATE UNIQUE INDEX "APOLLOPORTALDB"."USERS_UK_USERNAME_INDEX"
  ON "APOLLOPORTALDB"."USERS" ("USERNAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Foreign Keys structure for table SPRING_SESSION_ATTRIBUTES
-- ----------------------------
ALTER TABLE "APOLLOPORTALDB"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SPRING_SESSION_ATTRIBUTES_FK" FOREIGN KEY ("SESSION_PRIMARY_ID") REFERENCES "APOLLOPORTALDB"."SPRING_SESSION" ("PRIMARY_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
