-- DROP USER APOLLOPORTALDB;

CREATE USER APOLLOPORTALDB
-- IDENTIFIED BY <password>
;

CREATE TABLE "APP" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"NAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ORGID" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"ORGNAME" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"OWNERNAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"OWNEREMAIL" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127575" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127480" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127481" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127482" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127483" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127484" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127485" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127486" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127487" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127488" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127489" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127491" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127790" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127791" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127792" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127793" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127794" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127795" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127796" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127797" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127798" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127799" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127800" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129035" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129036" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129037" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129038" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129039" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129040" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129041" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129042" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129043" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129044" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129045" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127575" ON "APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "APP_DATACHANGE_LASTTIME_INDEX" ON "APP" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "APP_IX_NAME_INDEX" ON "APP" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "APP_UK_APPID_DELETEDAT_INDEX" ON "APP" ("APPID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.APP IS '应用表';
COMMENT ON COLUMN APOLLOPORTALDB.APP.ID IS '主键';
COMMENT ON COLUMN APOLLOPORTALDB.APP.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOPORTALDB.APP.NAME IS '应用名';
COMMENT ON COLUMN APOLLOPORTALDB.APP.ORGID IS '部门ID';
COMMENT ON COLUMN APOLLOPORTALDB.APP.ORGNAME IS '部门名字';
COMMENT ON COLUMN APOLLOPORTALDB.APP.OWNERNAME IS 'OWNERNAME';
COMMENT ON COLUMN APOLLOPORTALDB.APP.OWNEREMAIL IS 'OWNEREMAIL';
COMMENT ON COLUMN APOLLOPORTALDB.APP.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.APP.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.APP.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.APP.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.APP.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.APP.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "APPNAMESPACE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(32) DEFAULT '' NOT NULL ENABLE, 
	"APPID" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"FORMAT" NVARCHAR2(32) DEFAULT 'properties' NOT NULL ENABLE, 
	"ISPUBLIC" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"COMMENT" NVARCHAR2(64) DEFAULT '' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127576" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127490" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127493" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127495" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127497" CHECK ("FORMAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127499" CHECK ("ISPUBLIC" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127501" CHECK ("COMMENT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127503" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127505" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127507" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127509" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127801" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127802" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127803" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127804" CHECK ("FORMAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127805" CHECK ("ISPUBLIC" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127806" CHECK ("COMMENT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127807" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127808" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127809" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127810" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129046" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129047" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129048" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129049" CHECK ("FORMAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129050" CHECK ("ISPUBLIC" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129051" CHECK ("COMMENT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129052" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129053" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129054" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129055" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127576" ON "APPNAMESPACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "DATAAPPNAMESPACE_CHANGE_LASTTIME_INDEX" ON "APPNAMESPACE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "DATAAPPNAMESPACE_NAME_APPID_INDEX" ON "APPNAMESPACE" ("NAME", "APPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "DATAAPPNAMESPACE_UK_APPID_NAME_DELETEDAT_INDEX" ON "APPNAMESPACE" ("APPID", "NAME", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.APPNAMESPACE IS '应用NAMESPACE定义';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.ID IS '自增主键';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.NAME IS 'NAMESPACE名字，注意，需要全局唯一';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.APPID IS 'APP ID';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.FORMAT IS 'NAMESPACE的FORMAT类型';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.ISPUBLIC IS 'NAMESPACE是否为公共';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.APPNAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "AUTHORITIES" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"USERNAME" NVARCHAR2(64) NOT NULL ENABLE, 
	"AUTHORITY" NVARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C00127574" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127477" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127478" CHECK ("USERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127479" CHECK ("AUTHORITY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127811" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127812" CHECK ("USERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127813" CHECK ("AUTHORITY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129056" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129057" CHECK ("USERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129058" CHECK ("AUTHORITY" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127574" ON "AUTHORITIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON COLUMN APOLLOPORTALDB.AUTHORITIES.ID IS '自增ID';

CREATE TABLE "CONSUMER" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"NAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ORGID" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"ORGNAME" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"OWNERNAME" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"OWNEREMAIL" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127577" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127492" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127494" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127496" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127498" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127500" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127502" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127504" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127506" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127508" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127510" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127511" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127814" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127815" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127816" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127817" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127818" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127819" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127820" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127821" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127822" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127823" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127824" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129059" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129060" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129061" CHECK ("NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129062" CHECK ("ORGID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129063" CHECK ("ORGNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129064" CHECK ("OWNERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129065" CHECK ("OWNEREMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129066" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129067" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129068" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129069" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127577" ON "CONSUMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "AUTHORITIES_DATACHANGE_LASTTIME_INDEX" ON "CONSUMER" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "AUTHORITIES_UK_APPID_DELETEDAT_INDEX" ON "CONSUMER" ("APPID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.CONSUMER IS '开放API消费者';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.NAME IS '应用名';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.ORGID IS '部门ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.ORGNAME IS '部门名字';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.OWNERNAME IS 'OWNERNAME';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.OWNEREMAIL IS 'OWNEREMAIL';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMER.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "CONSUMERAUDIT" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"CONSUMERID" NUMBER(11,0), 
	"URI" NCLOB DEFAULT '' NOT NULL ENABLE, 
	"METHOD" NVARCHAR2(16) DEFAULT '' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127578" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127512" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127513" CHECK ("URI" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127514" CHECK ("METHOD" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127515" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127825" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127826" CHECK ("URI" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127827" CHECK ("METHOD" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127828" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129070" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129071" CHECK ("URI" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129072" CHECK ("METHOD" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129073" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
 LOB ("URI") STORE AS SECUREFILE (
  TABLESPACE "APOLLOPORTALDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "SYS_IL0000186940C00003$$" ON "CONSUMERAUDIT" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_C00127578" ON "CONSUMERAUDIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "CONSUMERAUDIT_IX_CONSUMERID_INDEX" ON "CONSUMERAUDIT" ("CONSUMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "CONSUMERAUDIT_IX_DATACHANGE_LASTTIME_INDEX" ON "CONSUMERAUDIT" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.CONSUMERAUDIT IS 'CONSUMER审计表';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERAUDIT.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERAUDIT.CONSUMERID IS 'CONSUMER ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERAUDIT.URI IS '访问的URI';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERAUDIT."METHOD" IS '访问的METHOD';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERAUDIT.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERAUDIT.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "CONSUMERROLE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"CONSUMERID" NUMBER(11,0), 
	"ROLEID" NUMBER(11,0), 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127581" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127517" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127520" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127523" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127526" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127529" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127829" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127830" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127831" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127832" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127833" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129074" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129075" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129076" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129077" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129078" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127581" ON "CONSUMERROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "CONSUMERROLE_IX_DATACHANGE_LASTTIME_INDEX" ON "CONSUMERROLE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "CONSUMERROLE_IX_ROLEID_INDEX" ON "CONSUMERROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "CONSUMERROLE_UK_CONSUMERID_ROLEID_DELETEDAT_INDEX" ON "CONSUMERROLE" ("CONSUMERID", "ROLEID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.CONSUMERROLE IS 'CONSUMER和ROLE的绑定表';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.CONSUMERID IS 'CONSUMER ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.ROLEID IS 'ROLE ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERROLE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "CONSUMERTOKEN" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"CONSUMERID" NUMBER(11,0), 
	"TOKEN" NVARCHAR2(128) DEFAULT '' NOT NULL ENABLE, 
	"EXPIRES" DATE DEFAULT TO_DATE('2090-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS') NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127579" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127518" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127521" CHECK ("TOKEN" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127524" CHECK ("EXPIRES" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127527" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127530" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127533" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127535" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127834" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127835" CHECK ("TOKEN" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127836" CHECK ("EXPIRES" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127837" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127838" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127839" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127840" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129079" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129080" CHECK ("TOKEN" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129081" CHECK ("EXPIRES" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129082" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129083" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129084" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129085" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127579" ON "CONSUMERTOKEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "CONSUMERTOKEN_DATACHANGE_LASTTIME_INDEX" ON "CONSUMERTOKEN" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "CONSUMERTOKEN_UK_TOKEN_DELETEDAT_INDEX" ON "CONSUMERTOKEN" ("TOKEN", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.CONSUMERTOKEN IS 'CONSUMER TOKEN表';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.CONSUMERID IS 'CONSUMERID';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.TOKEN IS 'TOKEN';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.EXPIRES IS 'TOKEN失效时间';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.CONSUMERTOKEN.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "FAVORITE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"USERID" NVARCHAR2(32) DEFAULT 'default' NOT NULL ENABLE, 
	"APPID" NVARCHAR2(500) DEFAULT 'default' NOT NULL ENABLE, 
	"POSITION" NUMBER(11,0) DEFAULT 10000 NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127580" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127516" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127519" CHECK ("USERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127522" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127525" CHECK ("POSITION" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127528" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127531" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127534" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127537" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127841" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127842" CHECK ("USERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127843" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127844" CHECK ("POSITION" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127845" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127846" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127847" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127848" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129086" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129087" CHECK ("USERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129088" CHECK ("APPID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129089" CHECK ("POSITION" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129090" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129091" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129092" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129093" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127580" ON "FAVORITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "FAVORITE_APPID_INDEX" ON "FAVORITE" ("APPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "FAVORITE_DATACHANGE_LASTTIME_INDEX" ON "FAVORITE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "FAVORITE_UK_USERID_APPID_DELETEDAT_INDEX" ON "FAVORITE" ("USERID", "APPID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.FAVORITE IS '应用收藏表';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.ID IS '主键';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.USERID IS '收藏的用户';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.APPID IS 'APPID';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE."POSITION" IS '收藏顺序';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.FAVORITE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "PERMISSION" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"PERMISSIONTYPE" NVARCHAR2(32) DEFAULT '' NOT NULL ENABLE, 
	"TARGETID" NVARCHAR2(256) DEFAULT '' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127582" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127532" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127536" CHECK ("PERMISSIONTYPE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127538" CHECK ("TARGETID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127539" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127540" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127541" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127542" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127849" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127850" CHECK ("PERMISSIONTYPE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127851" CHECK ("TARGETID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127852" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127853" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127854" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127855" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129094" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129095" CHECK ("PERMISSIONTYPE" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129096" CHECK ("TARGETID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129097" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129098" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129099" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129100" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127582" ON "PERMISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "PERMISSION_IX_DATACHANGE_LASTTIME_INDEX" ON "PERMISSION" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "PERMISSION_UK_TARGETID_PERMISSIONTYPE_DELETEDAT_INDEX" ON "PERMISSION" ("TARGETID", "PERMISSIONTYPE", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.PERMISSION IS 'PERMISSION表';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.PERMISSIONTYPE IS '权限类型';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.TARGETID IS '权限对象类型';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.PERMISSION.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "ROLE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"ROLENAME" NVARCHAR2(256) DEFAULT '' NOT NULL ENABLE, 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127583" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127543" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127544" CHECK ("ROLENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127545" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127546" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127547" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127548" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127856" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127857" CHECK ("ROLENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127858" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127859" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127860" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127861" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129101" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129102" CHECK ("ROLENAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129103" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129104" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129105" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129106" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127583" ON "ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "ROLE_IX_DATACHANGE_LASTTIME_INDEX" ON "ROLE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "ROLE_UK_ROLENAME_DELETEDAT_INDEX" ON "ROLE" ("ROLENAME", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB."ROLE" IS '角色表';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".ROLENAME IS 'ROLE NAME';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB."ROLE".DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "ROLEPERMISSION" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"ROLEID" NUMBER(11,0), 
	"PERMISSIONID" NUMBER(11,0), 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127585" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127555" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127556" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127557" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127558" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127560" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127862" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127863" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127864" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127865" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127866" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129107" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129108" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129109" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129110" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129111" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127585" ON "ROLEPERMISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "ROLEPERMISSION_IX_DATACHANGE_LASTTIME_INDEX" ON "ROLEPERMISSION" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "ROLEPERMISSION_IX_PERMISSIONID_INDEX" ON "ROLEPERMISSION" ("PERMISSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "ROLEPERMISSION_UK_ROLEID_PERMISSIONID_DELETEDAT_INDEX" ON "ROLEPERMISSION" ("ROLEID", "PERMISSIONID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.ROLEPERMISSION IS '角色和权限的绑定表';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.ROLEID IS 'ROLE ID';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.PERMISSIONID IS 'PERMISSION ID';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.ROLEPERMISSION.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "SERVERCONFIG" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"KEY" NVARCHAR2(64) DEFAULT 'default', 
	"VALUE" NCLOB DEFAULT 'default', 
	"COMMENT" NCLOB DEFAULT '', 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default', 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127586" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127559" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127867" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128732" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129112" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129113" CHECK ("ISDELETED" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
 LOB ("VALUE") STORE AS SECUREFILE (
  TABLESPACE "APOLLOPORTALDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("COMMENT") STORE AS SECUREFILE (
  TABLESPACE "APOLLOPORTALDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "SYS_IL0000186949C00004$$" ON "SERVERCONFIG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_IL0000186949C00003$$" ON "SERVERCONFIG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_C00127586" ON "SERVERCONFIG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "SERVERCONFIG_DATACHANGE_LASTTIME_INDEX" ON "SERVERCONFIG" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "SERVERCONFIG_UK_KEY_DELETEDAT_INDEX" ON "SERVERCONFIG" ("KEY", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.SERVERCONFIG IS '配置服务自身配置';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG."KEY" IS '配置项KEY';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.VALUE IS '配置项值';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.SERVERCONFIG.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "SPRING_SESSION" 
   (	"PRIMARY_ID" CHAR(36) NOT NULL ENABLE, 
	"SESSION_ID" CHAR(36) NOT NULL ENABLE, 
	"CREATION_TIME" NUMBER(19,0) NOT NULL ENABLE, 
	"LAST_ACCESS_TIME" NUMBER(19,0) NOT NULL ENABLE, 
	"MAX_INACTIVE_INTERVAL" NUMBER(10,0) NOT NULL ENABLE, 
	"EXPIRY_TIME" NUMBER(19,0) NOT NULL ENABLE, 
	"PRINCIPAL_NAME" VARCHAR2(100 CHAR), 
	 CONSTRAINT "SPRING_SESSION_PK" PRIMARY KEY ("PRIMARY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127980" CHECK ("PRIMARY_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127981" CHECK ("SESSION_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127982" CHECK ("CREATION_TIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127983" CHECK ("LAST_ACCESS_TIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127984" CHECK ("MAX_INACTIVE_INTERVAL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127985" CHECK ("EXPIRY_TIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128813" CHECK ("PRIMARY_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128814" CHECK ("SESSION_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128815" CHECK ("CREATION_TIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128816" CHECK ("LAST_ACCESS_TIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128817" CHECK ("MAX_INACTIVE_INTERVAL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00128818" CHECK ("EXPIRY_TIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SPRING_SESSION_PK" ON "SPRING_SESSION" ("PRIMARY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "SPRING_SESSION_IX1" ON "SPRING_SESSION" ("SESSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "SPRING_SESSION_IX2" ON "SPRING_SESSION" ("EXPIRY_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "SPRING_SESSION_IX3" ON "SPRING_SESSION" ("PRINCIPAL_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
;

CREATE TABLE "SPRING_SESSION_ATTRIBUTES" 
   (	"SESSION_PRIMARY_ID" CHAR(36) NOT NULL ENABLE, 
	"ATTRIBUTE_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_BYTES" BLOB NOT NULL ENABLE, 
	 CONSTRAINT "SPRING_SESSION_ATTRIBUTES_PK" PRIMARY KEY ("SESSION_PRIMARY_ID", "ATTRIBUTE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127987" CHECK ("SESSION_PRIMARY_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127988" CHECK ("ATTRIBUTE_NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127989" CHECK ("ATTRIBUTE_BYTES" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129114" CHECK ("SESSION_PRIMARY_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129115" CHECK ("ATTRIBUTE_NAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129116" CHECK ("ATTRIBUTE_BYTES" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
 LOB ("ATTRIBUTE_BYTES") STORE AS SECUREFILE (
  TABLESPACE "APOLLOPORTALDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

ALTER TABLE "SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SPRING_SESSION_ATTRIBUTES_FK" FOREIGN KEY ("SESSION_PRIMARY_ID")
	  REFERENCES "SPRING_SESSION" ("PRIMARY_ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SYS_IL0000186955C00003$$" ON "SPRING_SESSION_ATTRIBUTES" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SPRING_SESSION_ATTRIBUTES_PK" ON "SPRING_SESSION_ATTRIBUTES" ("SESSION_PRIMARY_ID", "ATTRIBUTE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
;

CREATE TABLE "USERROLE" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"USERID" NVARCHAR2(128) DEFAULT '', 
	"ROLEID" NUMBER(11,0), 
	"ISDELETED" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE, 
	"DELETEDAT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACHANGE_CREATEDBY" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"DATACHANGE_CREATEDTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) DEFAULT '', 
	"DATACHANGE_LASTTIME" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "SYS_C00127588" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127564" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127565" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127566" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127567" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127568" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127868" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127869" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127870" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127871" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127872" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129117" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129118" CHECK ("ISDELETED" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129119" CHECK ("DELETEDAT" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129120" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129121" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127588" ON "USERROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "USERROLE_IX_DATACHANGE_LASTTIME_INDEX" ON "USERROLE" ("DATACHANGE_LASTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE INDEX "USERROLE_IX_ROLEID_INDEX" ON "USERROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "USERROLE_UK_USERID_ROLEID_DELETEDAT_INDEX" ON "USERROLE" ("USERID", "ROLEID", "DELETEDAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.USERROLE IS '用户和ROLE的绑定表';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.USERID IS '用户身份标识';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.ROLEID IS 'ROLE ID';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.ISDELETED IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.DELETEDAT IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLOPORTALDB.USERROLE.DATACHANGE_LASTTIME IS '最后修改时间';

CREATE TABLE "USERS" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"USERNAME" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"PASSWORD" NVARCHAR2(512) DEFAULT 'default' NOT NULL ENABLE, 
	"USERDISPLAYNAME" NVARCHAR2(512) DEFAULT 'default' NOT NULL ENABLE, 
	"EMAIL" NVARCHAR2(64) DEFAULT 'default' NOT NULL ENABLE, 
	"ENABLED" NUMBER(4,0), 
	 CONSTRAINT "SYS_C00127589" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB"  ENABLE, 
	 CONSTRAINT "SYS_C00127569" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127570" CHECK ("USERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127571" CHECK ("PASSWORD" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127572" CHECK ("USERDISPLAYNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127573" CHECK ("EMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127873" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127874" CHECK ("USERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127875" CHECK ("PASSWORD" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127876" CHECK ("USERDISPLAYNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00127877" CHECK ("EMAIL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129122" CHECK ("ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129123" CHECK ("USERNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129124" CHECK ("PASSWORD" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129125" CHECK ("USERDISPLAYNAME" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C00129126" CHECK ("EMAIL" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

CREATE UNIQUE INDEX "SYS_C00127589" ON "USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;
  CREATE UNIQUE INDEX "USERS_UK_USERNAME_INDEX" ON "USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APOLLOPORTALDB" ;

COMMENT ON TABLE APOLLOPORTALDB.USERS IS '用户表';
COMMENT ON COLUMN APOLLOPORTALDB.USERS.ID IS '自增ID';
COMMENT ON COLUMN APOLLOPORTALDB.USERS.USERNAME IS '用户登录账户';
COMMENT ON COLUMN APOLLOPORTALDB.USERS.PASSWORD IS '密码';
COMMENT ON COLUMN APOLLOPORTALDB.USERS.USERDISPLAYNAME IS '用户名称';
COMMENT ON COLUMN APOLLOPORTALDB.USERS.EMAIL IS '邮箱地址';
COMMENT ON COLUMN APOLLOPORTALDB.USERS.ENABLED IS '是否有效';

CREATE SEQUENCE APOLLOPORTALDB.ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
