/*
 Navicat Oracle Data Transfer

 Source Server         : APOLLOPORTALDB
 Source Server Type    : Oracle
 Source Server Version : 120200 (Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production)
 Source Host           : 192.168.80.73:1521
 Source Schema         : APOLLOCONFIGDB

 Target Server Type    : Oracle
 Target Server Version : 120200 (Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production)
 File Encoding         : 65001

 Date: 17/05/2023 14:27:45
*/


-- ----------------------------
-- Table structure for ACCESSKEY
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."ACCESSKEY";
CREATE TABLE "APOLLOCONFIGDB"."ACCESSKEY" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "SECRET" NVARCHAR2(128) VISIBLE NOT NULL,
  "ISENABLED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."SECRET" IS 'SECRET';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."ISENABLED" IS '1: ENABLED, 0: DISABLED';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."ACCESSKEY" IS '访问密钥';

-- ----------------------------
-- Records of ACCESSKEY
-- ----------------------------

-- ----------------------------
-- Table structure for APP
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."APP";
CREATE TABLE "APOLLOCONFIGDB"."APP" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "ORGID" NVARCHAR2(32) VISIBLE NOT NULL,
  "ORGNAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "OWNERNAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "OWNEREMAIL" NVARCHAR2(500) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."NAME" IS '应用名';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ORGID" IS '部门ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ORGNAME" IS '部门名字';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."OWNERNAME" IS 'OWNERNAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."OWNEREMAIL" IS 'OWNEREMAIL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."APP" IS '应用表';

-- ----------------------------
-- Records of APP
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."APP" VALUES ('1', 'demo', 'demo', 'TEST1', '样例部门1', 'apollo', 'apollo@acme.com', '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:24', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2023-05-17 14:21:24', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for APPNAMESPACE
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."APPNAMESPACE";
CREATE TABLE "APOLLOCONFIGDB"."APPNAMESPACE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "FORMAT" NVARCHAR2(32) VISIBLE NOT NULL,
  "ISPUBLIC" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "COMMENT" NVARCHAR2(64) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."NAME" IS 'NAMESPACE名字，注意，需要全局唯一';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."APPID" IS 'APP ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."FORMAT" IS 'NAMESPACE的FORMAT类型';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."ISPUBLIC" IS 'NAMESPACE是否为公共';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."COMMENT" IS '注释';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."APPNAMESPACE" IS '应用NAMESPACE定义';

-- ----------------------------
-- Records of APPNAMESPACE
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."APPNAMESPACE" VALUES ('3', 'application', 'demo', 'properties', '0', 'default app namespace', '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for AUDIT
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."AUDIT";
CREATE TABLE "APOLLOCONFIGDB"."AUDIT" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "ENTITYNAME" NVARCHAR2(50) VISIBLE NOT NULL,
  "ENTITYID" NUMBER(11,0) VISIBLE,
  "OPNAME" NVARCHAR2(50) VISIBLE NOT NULL,
  "COMMENT" NVARCHAR2(500) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."ENTITYNAME" IS '表名';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."ENTITYID" IS '记录ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."OPNAME" IS '操作类型';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."COMMENT" IS '备注';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."AUDIT" IS '日志审计表';

-- ----------------------------
-- Records of AUDIT
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."AUDIT" VALUES ('2', 'App', '1', 'INSERT', NULL, '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."AUDIT" VALUES ('4', 'AppNamespace', '3', 'INSERT', NULL, '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."AUDIT" VALUES ('6', 'Cluster', '5', 'INSERT', NULL, '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."AUDIT" VALUES ('8', 'Namespace', '7', 'INSERT', NULL, '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."AUDIT" VALUES ('10', 'Item', '9', 'INSERT', NULL, '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:42', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-17 14:21:42', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for CLUSTER
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."CLUSTER";
CREATE TABLE "APOLLOCONFIGDB"."CLUSTER" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "PARENTCLUSTERID" NUMBER(11,0) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."NAME" IS '集群名字';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."APPID" IS 'APP ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."PARENTCLUSTERID" IS '父CLUSTER';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."CLUSTER" IS '集群';

-- ----------------------------
-- Records of CLUSTER
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."CLUSTER" VALUES ('5', 'default', 'demo', '0', '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for COMMIT
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."COMMIT";
CREATE TABLE "APOLLOCONFIGDB"."COMMIT" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CHANGESETS" NCLOB VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "CLUSTERNAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "NAMESPACENAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "COMMENT" NVARCHAR2(500) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."CHANGESETS" IS '修改变更集';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."CLUSTERNAME" IS 'CLUSTERNAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."NAMESPACENAME" IS 'NAMESPACENAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."COMMENT" IS '备注';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."COMMIT" IS 'COMMIT 历史表';

-- ----------------------------
-- Records of COMMIT
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."COMMIT" VALUES ('11', '{"createItems":[{"namespaceId":7,"key":"test","value":"value","comment":"111","lineNum":1,"id":9,"isDeleted":false,"deletedAt":0,"dataChangeCreatedBy":"apollo","dataChangeCreatedTime":"2023-05-17 14:21:42","dataChangeLastModifiedBy":"apollo","dataChangeLastModifiedTime":"2023-05-17 14:21:42"}],"updateItems":[],"deleteItems":[]}', 'demo', 'default', 'application', NULL, '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:42', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2023-05-17 14:21:42', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for GRAYRELEASERULE
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE";
CREATE TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "CLUSTERNAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "NAMESPACENAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "BRANCHNAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "RULES" NCLOB VISIBLE,
  "RELEASEID" NUMBER(11,0) VISIBLE NOT NULL,
  "BRANCHSTATUS" NUMBER(4,0) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."CLUSTERNAME" IS 'CLUSTER NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."NAMESPACENAME" IS 'NAMESPACE NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."BRANCHNAME" IS 'BRANCH NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."RULES" IS '灰度规则';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."RELEASEID" IS '灰度对应的RELEASE';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."BRANCHSTATUS" IS '灰度分支状态: 0:删除分支,1:正在使用的规则 2：全量发布';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" IS '灰度规则表';

-- ----------------------------
-- Records of GRAYRELEASERULE
-- ----------------------------

-- ----------------------------
-- Table structure for INSTANCE
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."INSTANCE";
CREATE TABLE "APOLLOCONFIGDB"."INSTANCE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "CLUSTERNAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "DATACENTER" NVARCHAR2(64) VISIBLE NOT NULL,
  "IP" NVARCHAR2(32) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTTIME" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."CLUSTERNAME" IS 'CLUSTERNAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."DATACENTER" IS 'DATA CENTER NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."IP" IS 'INSTANCE IP';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."INSTANCE" IS '使用配置的应用实例';

-- ----------------------------
-- Records of INSTANCE
-- ----------------------------

-- ----------------------------
-- Table structure for INSTANCECONFIG
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."INSTANCECONFIG";
CREATE TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "INSTANCEID" NUMBER(11,0) VISIBLE,
  "CONFIGAPPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "CONFIGCLUSTERNAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "CONFIGNAMESPACENAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "RELEASEKEY" NVARCHAR2(64) VISIBLE NOT NULL,
  "RELEASEDELIVERYTIME" DATE VISIBLE,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTTIME" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."INSTANCEID" IS 'INSTANCE ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."CONFIGAPPID" IS 'CONFIG APP ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."CONFIGCLUSTERNAME" IS 'CONFIG CLUSTER NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."CONFIGNAMESPACENAME" IS 'CONFIG NAMESPACE NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."RELEASEKEY" IS '发布的KEY';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."RELEASEDELIVERYTIME" IS '配置获取时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" IS '应用实例的配置信息';

-- ----------------------------
-- Records of INSTANCECONFIG
-- ----------------------------

-- ----------------------------
-- Table structure for ITEM
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."ITEM";
CREATE TABLE "APOLLOCONFIGDB"."ITEM" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "NAMESPACEID" NUMBER(11,0) VISIBLE NOT NULL,
  "KEY" NVARCHAR2(128) VISIBLE NOT NULL,
  "VALUE" NCLOB VISIBLE NOT NULL,
  "COMMENT" NCLOB VISIBLE,
  "LINENUM" NUMBER(11,0) VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."NAMESPACEID" IS '集群NAMESPACEID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."KEY" IS '配置项KEY';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."VALUE" IS '配置项值';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."COMMENT" IS '注释';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."LINENUM" IS '行号';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."ITEM" IS '配置项目';

-- ----------------------------
-- Records of ITEM
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."ITEM" VALUES ('9', '7', 'test', 'value', '111', '1', '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:42', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2023-05-17 14:21:42', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for NAMESPACE
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."NAMESPACE";
CREATE TABLE "APOLLOCONFIGDB"."NAMESPACE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "CLUSTERNAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "NAMESPACENAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."CLUSTERNAME" IS 'CLUSTER NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."NAMESPACENAME" IS 'NAMESPACE NAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."NAMESPACE" IS '命名空间';

-- ----------------------------
-- Records of NAMESPACE
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."NAMESPACE" VALUES ('7', 'demo', 'default', 'application', '0', '0', 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2023-05-17 14:21:25', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for NAMESPACELOCK
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."NAMESPACELOCK";
CREATE TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "NAMESPACEID" NUMBER(11,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."NAMESPACEID" IS '集群NAMESPACEID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."ISDELETED" IS '软删除';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" IS 'NAMESPACE的编辑锁';

-- ----------------------------
-- Records of NAMESPACELOCK
-- ----------------------------

-- ----------------------------
-- Table structure for RELEASE
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."RELEASE";
CREATE TABLE "APOLLOCONFIGDB"."RELEASE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "RELEASEKEY" NVARCHAR2(64) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "COMMENT" NVARCHAR2(256) VISIBLE,
  "APPID" NVARCHAR2(500) VISIBLE NOT NULL,
  "CLUSTERNAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "NAMESPACENAME" NVARCHAR2(500) VISIBLE NOT NULL,
  "CONFIGURATIONS" NCLOB VISIBLE NOT NULL,
  "ISABANDONED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."RELEASEKEY" IS '发布的KEY';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."NAME" IS '发布名字';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."COMMENT" IS '发布说明';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."CLUSTERNAME" IS 'CLUSTERNAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."NAMESPACENAME" IS 'NAMESPACENAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."CONFIGURATIONS" IS '发布配置';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."ISABANDONED" IS '是否废弃';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."RELEASE" IS '发布';

-- ----------------------------
-- Records of RELEASE
-- ----------------------------

-- ----------------------------
-- Table structure for RELEASEHISTORY
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."RELEASEHISTORY";
CREATE TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APPID" NVARCHAR2(64) VISIBLE NOT NULL,
  "CLUSTERNAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "NAMESPACENAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "BRANCHNAME" NVARCHAR2(32) VISIBLE NOT NULL,
  "RELEASEID" NUMBER(11,0) VISIBLE NOT NULL,
  "PREVIOUSRELEASEID" NUMBER(11,0) VISIBLE NOT NULL,
  "OPERATION" NUMBER(4,0) VISIBLE NOT NULL,
  "OPERATIONCONTEXT" NCLOB VISIBLE NOT NULL,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE NOT NULL,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE NOT NULL,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."CLUSTERNAME" IS 'CLUSTERNAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."NAMESPACENAME" IS 'NAMESPACENAME';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."BRANCHNAME" IS '发布分支名';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."RELEASEID" IS '关联的RELEASE ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."PREVIOUSRELEASEID" IS '前一次发布的RELEASEID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."OPERATION" IS '发布类型，0: 普通发布，1: 回滚，2: 灰度发布，3: 灰度规则更新，4: 灰度合并回主分支发布，5: 主分支发布灰度自动发布，6: 主分支回滚灰度自动发布，7: 放弃灰度';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."OPERATIONCONTEXT" IS '发布上下文信息';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" IS '发布历史';

-- ----------------------------
-- Records of RELEASEHISTORY
-- ----------------------------

-- ----------------------------
-- Table structure for RELEASEMESSAGE
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE";
CREATE TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "MESSAGE" NCLOB VISIBLE NOT NULL,
  "DATACHANGE_LASTTIME" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEMESSAGE"."ID" IS '自增主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEMESSAGE"."MESSAGE" IS '发布的消息内容';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEMESSAGE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" IS '发布消息';

-- ----------------------------
-- Records of RELEASEMESSAGE
-- ----------------------------

-- ----------------------------
-- Table structure for SERVERCONFIG
-- ----------------------------
DROP TABLE "APOLLOCONFIGDB"."SERVERCONFIG";
CREATE TABLE "APOLLOCONFIGDB"."SERVERCONFIG" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "KEY" NVARCHAR2(64) VISIBLE,
  "CLUSTER" NVARCHAR2(32) VISIBLE,
  "VALUE" NCLOB VISIBLE,
  "COMMENT" NCLOB VISIBLE,
  "ISDELETED" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "DELETEDAT" NUMBER(20,0) VISIBLE,
  "DATACHANGE_CREATEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_CREATEDTIME" DATE VISIBLE,
  "DATACHANGE_LASTMODIFIEDBY" NVARCHAR2(64) VISIBLE,
  "DATACHANGE_LASTTIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."ID" IS '自增ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."KEY" IS '配置项KEY';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."CLUSTER" IS '配置对应的集群，DEFAULT为不针对特定的集群';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."VALUE" IS '配置项值';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."COMMENT" IS '注释';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."ISDELETED" IS '1: DELETED, 0: NORMAL';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DELETEDAT" IS 'DELETE TIMESTAMP BASED ON MILLISECONDS';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_CREATEDBY" IS '创建人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人邮箱前缀';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."SERVERCONFIG" IS '配置服务自身配置';

-- ----------------------------
-- Records of SERVERCONFIG
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('1', 'eureka.service.url', 'default', 'http://localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔', '0', '0', 'default', TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('2', 'namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关', '0', '0', 'default', TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('3', 'item.key.length.limit', 'default', '128', 'item key 最大长度限制', '0', '0', 'default', TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('4', 'item.value.length.limit', 'default', '20000', 'item value最大长度限制', '0', '0', 'default', TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('5', 'config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！', '0', '0', 'default', TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2023-05-16 16:54:31', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Sequence structure for ID_SEQ
-- ----------------------------
DROP SEQUENCE "APOLLOCONFIGDB"."ID_SEQ";
CREATE SEQUENCE "APOLLOCONFIGDB"."ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table ACCESSKEY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128399" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ACCESSKEY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128283" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128286" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128289" CHECK ("SECRET" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128292" CHECK ("ISENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128295" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128298" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128301" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128304" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128306" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128414" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128415" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128416" CHECK ("SECRET" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128417" CHECK ("ISENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128418" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128419" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128420" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128421" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C00128422" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ACCESSKEY
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."ACCESSKEY_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."ACCESSKEY" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."ACCESSKEY_UK_APPID_SECRET_DELETEDAT"
  ON "APOLLOCONFIGDB"."ACCESSKEY" ("APPID" ASC, "SECRET" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table APP
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128401" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APP
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128278" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128280" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128282" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128285" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128288" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128291" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128294" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128297" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128300" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128303" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128305" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128423" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128424" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128425" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128426" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128427" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128428" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128429" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128430" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128431" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128432" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C00128433" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APP
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APP_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."APP" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."APP_IX_NAME"
  ON "APOLLOCONFIGDB"."APP" ("NAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."APP_UK_APPID_DELETEDAT"
  ON "APOLLOCONFIGDB"."APP" ("APPID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128400" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128277" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128279" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128281" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128284" CHECK ("FORMAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128287" CHECK ("ISPUBLIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128290" CHECK ("COMMENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128293" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128296" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128299" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128302" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128434" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128435" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128436" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128437" CHECK ("FORMAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128438" CHECK ("ISPUBLIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128439" CHECK ("COMMENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128440" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128441" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128442" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C00128443" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APPNAMESPACE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APPNAMESPACE_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."APPNAMESPACE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."APPNAMESPACE_NAME_APPID"
  ON "APOLLOCONFIGDB"."APPNAMESPACE" ("NAME" ASC, "APPID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."APPNAMESPACE_UK_APPID_NAME_DELETEDAT"
  ON "APOLLOCONFIGDB"."APPNAMESPACE" ("APPID" ASC, "NAME" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUDIT
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128398" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table AUDIT
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128270" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128271" CHECK ("ENTITYNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128272" CHECK ("OPNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128273" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128274" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128275" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128276" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128444" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128445" CHECK ("ENTITYNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128446" CHECK ("OPNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128447" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128448" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128449" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT" ADD CONSTRAINT "SYS_C00128450" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUDIT
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."AUDIT_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."AUDIT" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CLUSTER
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128402" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CLUSTER
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128307" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128308" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128309" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128310" CHECK ("PARENTCLUSTERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128311" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128312" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128313" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128314" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128451" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128452" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128453" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128454" CHECK ("PARENTCLUSTERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128455" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128456" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128457" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER" ADD CONSTRAINT "SYS_C00128458" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CLUSTER
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."CLUSTER_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."CLUSTER" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."CLUSTER_IX_PARENTCLUSTERID"
  ON "APOLLOCONFIGDB"."CLUSTER" ("PARENTCLUSTERID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."CLUSTER_UK_APPID_NAME_DELETEDAT"
  ON "APOLLOCONFIGDB"."CLUSTER" ("APPID" ASC, "NAME" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table COMMIT
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128404" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table COMMIT
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128322" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128323" CHECK ("CHANGESETS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128324" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128325" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128326" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128327" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128328" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128329" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128330" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128459" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128460" CHECK ("CHANGESETS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128461" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128462" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128463" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128464" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128465" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128466" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C00128467" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table COMMIT
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."COMMIT_APPID"
  ON "APOLLOCONFIGDB"."COMMIT" ("APPID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."COMMIT_CLUSTERNAME"
  ON "APOLLOCONFIGDB"."COMMIT" ("CLUSTERNAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."COMMIT_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."COMMIT" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."COMMIT_NAMESPACENAME"
  ON "APOLLOCONFIGDB"."COMMIT" ("NAMESPACENAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table GRAYRELEASERULE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128403" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GRAYRELEASERULE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128331" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128332" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128333" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128334" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128335" CHECK ("BRANCHNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128336" CHECK ("RELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128337" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128338" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128339" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128340" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128468" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128469" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128470" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128471" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128472" CHECK ("BRANCHNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128473" CHECK ("RELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128474" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128475" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128476" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C00128477" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table GRAYRELEASERULE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."GRAYRELEASERULE_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."GRAYRELEASERULE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."GRAYRELEASERULE_IX_NAMESPACE"
  ON "APOLLOCONFIGDB"."GRAYRELEASERULE" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table INSTANCE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128405" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table INSTANCE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128315" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128316" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128317" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128318" CHECK ("DATACENTER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128319" CHECK ("IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128320" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128321" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128478" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128479" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128480" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128481" CHECK ("DATACENTER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128482" CHECK ("IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128483" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C00128484" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table INSTANCE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."INSTANCE_IX_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."INSTANCE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."INSTANCE_IX_IP"
  ON "APOLLOCONFIGDB"."INSTANCE" ("IP" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."INSTANCE_IX_UNIQUE_KEY"
  ON "APOLLOCONFIGDB"."INSTANCE" ("APPID" ASC, "CLUSTERNAME" ASC, "IP" ASC, "DATACENTER" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table INSTANCECONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128406" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table INSTANCECONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128341" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128342" CHECK ("CONFIGAPPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128343" CHECK ("CONFIGCLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128344" CHECK ("CONFIGNAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128345" CHECK ("RELEASEKEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128346" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128347" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128485" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128486" CHECK ("CONFIGAPPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128487" CHECK ("CONFIGCLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128488" CHECK ("CONFIGNAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128489" CHECK ("RELEASEKEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128490" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C00128491" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table INSTANCECONFIG
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."INSTANCECONFIG_IX_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."INSTANCECONFIG_IX_RELEASEKEY"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("RELEASEKEY" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."INSTANCECONFIG_IX_UNIQUE_KEY"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("INSTANCEID" ASC, "CONFIGAPPID" ASC, "CONFIGNAMESPACENAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."INSTANCECONFIG_IX_VALID_NAMESPACE"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("CONFIGAPPID" ASC, "CONFIGCLUSTERNAME" ASC, "CONFIGNAMESPACENAME" ASC, "DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table ITEM
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128407" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ITEM
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128348" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128349" CHECK ("NAMESPACEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128350" CHECK ("KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128351" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128352" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128353" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128354" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128355" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128492" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128493" CHECK ("NAMESPACEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128494" CHECK ("KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128495" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128496" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128497" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128498" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C00128499" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ITEM
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."ITEM_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."ITEM" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."ITEM_IX_GROUPID"
  ON "APOLLOCONFIGDB"."ITEM" ("NAMESPACEID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table NAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128408" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table NAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128356" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128357" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128358" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128359" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128360" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128361" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128362" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128363" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128500" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128501" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128502" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128503" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128504" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128505" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128506" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C00128507" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table NAMESPACE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."NAMESPACE_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."NAMESPACE_IX_NAMESPACENAME"
  ON "APOLLOCONFIGDB"."NAMESPACE" ("NAMESPACENAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."NAMESPACE_UK_APPID_CLUSTERNAME_NAMESPACENAME_DELETEDAT"
  ON "APOLLOCONFIGDB"."NAMESPACE" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table NAMESPACELOCK
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128409" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table NAMESPACELOCK
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128364" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128365" CHECK ("NAMESPACEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128366" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128367" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128368" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128508" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128509" CHECK ("NAMESPACEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128510" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128511" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C00128512" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table NAMESPACELOCK
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."NAMESPACELOCK_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."NAMESPACELOCK" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."NAMESPACELOCK_UK_NAMESPACEID_DELETEDAT"
  ON "APOLLOCONFIGDB"."NAMESPACELOCK" ("NAMESPACEID" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table RELEASE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128410" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RELEASE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128371" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128373" CHECK ("RELEASEKEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128375" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128377" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128379" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128381" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128382" CHECK ("CONFIGURATIONS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128384" CHECK ("ISABANDONED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128386" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128388" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128390" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128392" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128513" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128514" CHECK ("RELEASEKEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128515" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128516" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128517" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128518" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128519" CHECK ("CONFIGURATIONS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128520" CHECK ("ISABANDONED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128521" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128522" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128523" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE" ADD CONSTRAINT "SYS_C00128524" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."RELEASE_APPID_CLUSTERNAME_GROUPNAME"
  ON "APOLLOCONFIGDB"."RELEASE" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."RELEASE_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."RELEASE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."RELEASE_UK_RELEASEKEY_DELETEDAT"
  ON "APOLLOCONFIGDB"."RELEASE" ("RELEASEKEY" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table RELEASEHISTORY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128411" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RELEASEHISTORY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128369" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128370" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128372" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128374" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128376" CHECK ("BRANCHNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128378" CHECK ("RELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128380" CHECK ("PREVIOUSRELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128383" CHECK ("OPERATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128385" CHECK ("OPERATIONCONTEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128387" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128389" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128391" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128393" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128525" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128526" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128527" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128528" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128529" CHECK ("BRANCHNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128530" CHECK ("RELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128531" CHECK ("PREVIOUSRELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128532" CHECK ("OPERATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128533" CHECK ("OPERATIONCONTEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128534" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128535" CHECK ("DELETEDAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128536" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C00128537" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASEHISTORY
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."RELEASEHISTORY_IX_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."RELEASEHISTORY" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."RELEASEHISTORY_IX_NAMESPACE"
  ON "APOLLOCONFIGDB"."RELEASEHISTORY" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC, "BRANCHNAME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "APOLLOCONFIGDB"."RELEASEHISTORY_IX_RELEASEID"
  ON "APOLLOCONFIGDB"."RELEASEHISTORY" ("RELEASEID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table RELEASEMESSAGE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128412" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RELEASEMESSAGE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128394" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128395" CHECK ("MESSAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128396" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128538" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128539" CHECK ("MESSAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C00128540" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASEMESSAGE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."RELEASEMESSAGE_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."RELEASEMESSAGE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00128413" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00128397" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00128541" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C00128733" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SERVERCONFIG
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."SERVERCONFIG_DATACHANGE_LASTTIME"
  ON "APOLLOCONFIGDB"."SERVERCONFIG" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."SERVERCONFIG_UK_KEY_CLUSTER_DELETEDAT"
  ON "APOLLOCONFIGDB"."SERVERCONFIG" ("KEY" ASC, "CLUSTER" ASC, "DELETEDAT" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
